### PR TITLE
Adding Functionality To Open 64 Bit Wave Files

### PR DESCRIPTION
**Pull request by prgarg007**

### CODE REVIEW

**Comment by Sato-Kunihiko** [comment]
@prgarg007 
Sorry for my late response.

The wave library supports 16 bit PCM only. 
I think your code has two complexities.
1. The wave and librosa library both are used for reading a wav file. 
2. The `temp` file is temporally saved for handling variant bits.

I suggest two ideas.
1. The code for changing a 64-bit file to 16-bit one should be implemented separately from `create_mixed_audio_file.py`.
2. The wave library should be replaced with the librosa completely.
 
Which do you think is better, or do you have other ideas?

**Comment by prgarg007** [comment]
Appreciate your reply. In my proposed changes only the audio which cannot be read by the wav library are changed to 16 bit. As I feel it would be difficult for some users to check for 64 & 16 bit wave files. The audios which are already 16bit OR which can be read by the wav library are used as it is. 
And for temp file : The temp file is the converted audio to 16bit which is removed as soon as the noise is added and saved to the directory.
Yes the librosa library can be only used for reading of wave files . Completely agree on that.
I want to know your thoughts on idea of only using the librosa library.

**Comment by Gabibing** [comment]
I think it is good idea to support other kinds of wav audio. 24bits, 32bits etc...

**Comment by prgarg007** [comment]
On further analysis of code & some testing's done by me I found only librosa cannot be used. As saving files using wav library gave me better & clean results in most of the cases. So using both the libraries alternatively seems to me a better choice. Any of your further comments will be appreciated.

**Comment by Sato-Kunihiko** [comment]
@prgarg007 @Gabibing 
Thank you for your comments.

I create a new pull request for the new file that can handle wav files with various encoding types. Any comments will be appreciated.
https://github.com/Sato-Kunihiko/audio-SNR/pull/10

The librosa package uses the soundfile library for reading a wav file. For more flexible code, using the soundfile is a better choice.
https://librosa.org/doc/latest/ioformats.html

**Pull request closed without merging**
